class RegistrationLocators:
    FIRST_NAME = ("xpath", "//*[@id='register_form']/fieldset[1]/p[1]/input")
    LAST_NAME = ("xpath", "//*[@id='register_form']//p[2]/input[1]")
    HOBBY = ("xpath", "//*[@name='hobby']")
    PHONE_NUMBER = ("xpath", "//*[@name='phone'and@type='text']")
    USERNAME = ("xpath", "//*[@name='username'and@type='text']")
    EMAIL = ("xpath", "//*[@name='email'and@type='text']")
    PASSWORD = ("xpath", "//*[@type='password'and@name='password']")
    CONFIRM_PASSWORD = ("xpath", "//*[@type='password'and@name='c_password']")
    BTN_SUBMIT = ("xpath", "//*[@value='submit'and@type='submit']")
    MSG_FIELD_IS_REQUIRED = ("css selector", "label.error_p")
